volumes:
  db_data:
  static_volume:

services:
  db:
    image: postgres:16
    volumes:
      - db_data:/var/lib/postgresql/data
    environment:
      POSTGRES_USER: ${POSTGRES_USER}
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD}
      POSTGRES_DB: ${POSTGRES_DB}
  
  backend:
    depends_on:
      - db
    image: andriyshkoy/burnote-backend:latest
    env_file:
      - .env
    volumes:
      - static_volume:/burnote/burnote/static

    command:
      gunicorn --bind 0.0.0.0:8000 manage:app

  nginx:
    depends_on:
      - backend
    image: andriyshkoy/burnote-nginx:latest
    env_file:
      - .env
    ports:
      - 14082:80
    volumes:
      - static_volume:/static
